### ISSUE TITLE
the sentence representations?

### ISSUE THREAD

**Issue by yanjieG** [DFKI-NLP/DISTRE#2]
Hi, I wonder how you obtain the sentence representation.
In your paper:

> A sentence representation is obtained by feeding the token sequence xi of a sentence to the pre-trained model and using the last state of the final state representation hL as its representation si. 

Is the sentence representations are the last state of '[CLS]' or something else?  I am confused about that. 
Would you please explain that for me? Thanks a lot.

Best

**Comment by ChristophAlt** [comment]
Hi,
your understanding is correct. The sentence representation is the last layer state of the [CLS] token.

**Comment by yanjieG** [comment]
OK, thanks a lot.
Have a nice day.

**Comment by charosen** [comment]
@yanjieG did you reproduce the 0.422 results by training your own DISTRE model?
