### ISSUE TITLE
About the NYT dataset.

### ISSUE THREAD

**Issue by airflier** [DFKI-NLP/DISTRE#8]
How could I get the NYT dataset now?
Thanks.

**Comment by leonhardhennig** [comment]
Hi,
I've updated the links, there is now a link to a copy of the original OpenNRE version: https://dfkide-my.sharepoint.com/:u:/g/personal/lehe02_dfki_de/EcCAEQhsKYNHlqoFq8m-3HgBbllwovMmjZjozqyTylh52w?Web=0&Download=1
Best, Leo
