### ISSUE TITLE
No file found at https://cloud.dfki.de/owncloud/index.php/s/kKdpoaGikWnL4tn/download

### ISSUE THREAD

**Issue by rathorevipul28** [DFKI-NLP/DISTRE#9]
OpenAI gpt model file cannot be found at https://cloud.dfki.de/owncloud/index.php/s/kKdpoaGikWnL4tn/download. Please tell the correct location.

**Comment by leonhardhennig** [comment]
Hi,
I've updated the links, there was an issue with DFKI's cloud storage.
Best, Leo
